language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip3 install http://download.pytorch.org/whl/cpu/torch-0.4.0-cp36-cp36m-linux_x86_64.whl
  - pip3 install torchvision
  - python setup.py develop
# command to run tests
script:
  - nosetests tests # or py.test for Python versions 3.5 and below